### PR TITLE
Dark influences

### LINKED ISSUE #1: Theme fixes
I've [commented out the dark theme for now](https://github.com/jakearchibald/linear-easing-generator/blob/main/src/static-build/pages/index/styles.module.css#L35). I could use some help making it 'right'.

Some things that feel like they need a fix-up:

- The accent color on the border of the 'format' and 'duration' inputs seems hard to see
- The gridlines on the graph seem hard to see
- The red used for the 'input' seems a bit garish?
- The thumb of range inputs seems hard to see. This might be a problem in the light view too.

Anything else you see?

If you don't have time for this, don't worry about it, I'll just ship without dark mode for v1.

### PR DESCRIPTION
**Pull request by argyleink**
fixes #1

### CODE REVIEW

**Comment by jakearchibald** [comment]
Ohh, thanks for picking this up!

It feels like the select & icon outlines should be lighter than the background. Same with the range track.

As in, current:

Screenshot 2023-07-04 at 08 29 17

Screenshot 2023-07-04 at 08 29 25

vs

Screenshot 2023-07-04 at 08 30 54

Screenshot 2023-07-04 at 08 32 25

wdyt? Less sure about the outline of the range input thumb, now I look at it here I think that looks better darker.

**Comment by argyleink** [comment]
> It feels like the select & icon outlines should be lighter than the background. Same with the range track.

great thoughts and requests! I've got them all in this latest commit except the slider track color, i tend to keep tracks as a "deeper" appearance to match the sorta skeuomorphic expectations we have with tracks. but i could be swayed to lighten it if you want!

**Review by jakearchibald — APPROVED** [review]
Slam-dunk LGTM. Sorry it took me so long to review it.

**Comment by jakearchibald** [comment]
> "deeper" appearance to match the sorta skeuomorphic expectations we have with tracks. but i could be swayed to lighten it if you want!

Nah, now I see it, you're right. Thanks for this!

**Pull request merged**
